        if(tb11.tellg()==0)
        {
            tb11.close();
            tb21.close();
            ta11.close();
            ta21.close();
            break;
        }
        tb11.close();
        tb21.close();
        ta11.close();
        ta21.close();
        length=length*2;